export const data = [
  {
    _id: "653958a8c3ec16c7e6efcc57",
    index: 0,
    guid: "3f4ada8d-7913-4c22-a72a-1124a992c432",
    isActive: false,
    balance: "$3,122.91",
    picture: "http://placehold.it/32x32",
    age: 24,
    eyeColor: "brown",
    name: "Shepherd Trevino",
    gender: "male",
    company: "TETRATREX",
    email: "shepherdtrevino@tetratrex.com",
    phone: "+1 (814) 595-2436",
    address: "123 Perry Place, Sardis, Wisconsin, 9036",
    about:
      "Lorem id officia ullamco ex id id nostrud ex aliquip. Lorem incididunt id in pariatur consectetur ad. Est deserunt magna laboris quis est voluptate dolore dolore ipsum dolor consectetur anim nostrud do. Non nostrud labore nulla quis aliqua id sit aliqua enim voluptate sit ad.\r\n",
    registered: "2017-11-14T03:01:40 -06:-30",
    latitude: 89.10613,
    longitude: -84.696701,
    tags: ["do", "id", "consequat", "cillum", "fugiat", "labore", "cillum"],
    friends: [
      {
        id: 0,
        name: "Miriam Sweeney",
      },
      {
        id: 1,
        name: "Jeri Everett",
      },
      {
        id: 2,
        name: "Wiley Rose",
      },
    ],
    greeting: "Hello, Shepherd Trevino! You have 8 unread messages.",
    favoriteFruit: "banana",
  },
  {
    _id: "653958a8cded0d7ca369d3a1",
    index: 1,
    guid: "54512868-10d9-4fca-a047-1b6d1e28976c",
    isActive: false,
    balance: "$3,256.87",
    picture: "http://placehold.it/32x32",
    age: 37,
    eyeColor: "brown",
    name: "Cynthia Kim",
    gender: "female",
    company: "ICOLOGY",
    email: "cynthiakim@icology.com",
    phone: "+1 (890) 420-3058",
    address: "758 Vandervoort Avenue, Gwynn, North Carolina, 840",
    about:
      "Sunt adipisicing tempor eiusmod ullamco id enim Lorem. Elit quis voluptate aliqua non consectetur aliqua Lorem occaecat voluptate dolore nulla cillum minim magna. Veniam nostrud in voluptate aliqua irure. Occaecat nisi proident et minim labore veniam est amet sit exercitation tempor. Exercitation ad ut esse velit laborum nisi cupidatat irure et aliquip.\r\n",
    registered: "2021-07-01T04:26:25 -06:-30",
    latitude: -13.038742,
    longitude: -120.138438,
    tags: [
      "eu",
      "dolor",
      "enim",
      "adipisicing",
      "dolore",
      "aliqua",
      "pariatur",
    ],
    friends: [
      {
        id: 0,
        name: "Winifred Underwood",
      },
      {
        id: 1,
        name: "Mayra May",
      },
      {
        id: 2,
        name: "Leann Livingston",
      },
    ],
    greeting: "Hello, Cynthia Kim! You have 1 unread messages.",
    favoriteFruit: "apple",
  },
  {
    _id: "653958a8cfd0821dd3ff076a",
    index: 2,
    guid: "040de95c-0529-4288-bd72-a0d3d08fbca0",
    isActive: false,
    balance: "$2,204.46",
    picture: "http://placehold.it/32x32",
    age: 39,
    eyeColor: "brown",
    name: "Knox Stuart",
    gender: "male",
    company: "ZBOO",
    email: "knoxstuart@zboo.com",
    phone: "+1 (938) 460-3020",
    address: "417 Burnett Street, Winchester, Utah, 1114",
    about:
      "Adipisicing ad et eiusmod ullamco tempor Lorem in officia veniam nostrud dolore excepteur in laboris. Laboris in in nulla ut elit. Aliqua magna officia ad ipsum magna laborum dolore esse tempor officia sunt ullamco mollit magna. Voluptate labore irure irure incididunt sint in ea dolor qui adipisicing.\r\n",
    registered: "2021-04-11T01:20:39 -06:-30",
    latitude: -47.909543,
    longitude: 47.240144,
    tags: ["non", "anim", "commodo", "est", "sint", "amet", "quis"],
    friends: [
      {
        id: 0,
        name: "Kathryn Hyde",
      },
      {
        id: 1,
        name: "Miller Moody",
      },
      {
        id: 2,
        name: "Duke Irwin",
      },
    ],
    greeting: "Hello, Knox Stuart! You have 5 unread messages.",
    favoriteFruit: "strawberry",
  },
  {
    _id: "653958a8eddc62bb9d73bf67",
    index: 3,
    guid: "50294174-2cce-4d58-9e1b-df2ec030d14c",
    isActive: false,
    balance: "$2,442.32",
    picture: "http://placehold.it/32x32",
    age: 34,
    eyeColor: "green",
    name: "Fernandez Olson",
    gender: "male",
    company: "MICRONAUT",
    email: "fernandezolson@micronaut.com",
    phone: "+1 (929) 427-2641",
    address: "848 Bergen Street, Hamilton, Delaware, 7270",
    about:
      "Exercitation incididunt exercitation voluptate dolor. Eiusmod dolor tempor aliqua commodo laboris velit tempor fugiat adipisicing tempor ipsum magna culpa. Adipisicing minim irure consequat excepteur deserunt adipisicing quis exercitation ea cupidatat. Cillum sit deserunt do velit minim adipisicing voluptate voluptate eu sunt amet qui consectetur. Laboris irure sit do labore magna id irure commodo do labore ipsum. Aliquip voluptate excepteur ea aliqua reprehenderit velit do in. Laborum ex occaecat consectetur anim et occaecat aliquip sit exercitation irure in nostrud cupidatat.\r\n",
    registered: "2014-03-28T05:14:47 -06:-30",
    latitude: -51.838604,
    longitude: -139.153126,
    tags: [
      "deserunt",
      "pariatur",
      "velit",
      "deserunt",
      "consequat",
      "anim",
      "dolore",
    ],
    friends: [
      {
        id: 0,
        name: "Alford Mccullough",
      },
      {
        id: 1,
        name: "Soto Mccormick",
      },
      {
        id: 2,
        name: "Herring Kent",
      },
    ],
    greeting: "Hello, Fernandez Olson! You have 2 unread messages.",
    favoriteFruit: "banana",
  },
  {
    _id: "653958a82eeebcda33ef08c9",
    index: 4,
    guid: "84fbf189-3d21-49c3-ae80-15cfa22b728c",
    isActive: true,
    balance: "$2,850.99",
    picture: "http://placehold.it/32x32",
    age: 39,
    eyeColor: "blue",
    name: "Powers Mcknight",
    gender: "male",
    company: "UNDERTAP",
    email: "powersmcknight@undertap.com",
    phone: "+1 (972) 543-2849",
    address: "974 Billings Place, Goochland, Illinois, 2311",
    about:
      "Lorem voluptate ipsum do ullamco elit amet adipisicing. Eu mollit voluptate ex exercitation enim Lorem ex aliquip nisi culpa minim amet. Ullamco in veniam occaecat ipsum. Elit ex ad magna non consectetur laboris consectetur velit cillum sunt aliquip in. Dolor ullamco exercitation esse mollit officia. Qui excepteur deserunt quis nulla. Consectetur occaecat adipisicing deserunt labore sit laborum aliquip.\r\n",
    registered: "2014-06-11T08:15:18 -06:-30",
    latitude: -58.320341,
    longitude: 152.048927,
    tags: ["et", "irure", "consectetur", "magna", "est", "veniam", "officia"],
    friends: [
      {
        id: 0,
        name: "Joni Roman",
      },
      {
        id: 1,
        name: "Lisa Collier",
      },
      {
        id: 2,
        name: "Reynolds Flores",
      },
    ],
    greeting: "Hello, Powers Mcknight! You have 10 unread messages.",
    favoriteFruit: "apple",
  },
  {
    _id: "653958a8e6a7515f9a007970",
    index: 5,
    guid: "9c3cffcf-ba26-4b2c-9fce-e312be8a7532",
    isActive: true,
    balance: "$3,578.73",
    picture: "http://placehold.it/32x32",
    age: 34,
    eyeColor: "blue",
    name: "Letha Wood",
    gender: "female",
    company: "VETRON",
    email: "lethawood@vetron.com",
    phone: "+1 (803) 532-2397",
    address: "850 Lombardy Street, Sabillasville, Texas, 978",
    about:
      "Labore aute ex incididunt nisi elit consectetur est duis eiusmod est. Velit ullamco elit culpa ad irure culpa fugiat in aliquip anim esse. Adipisicing cupidatat duis qui reprehenderit adipisicing. Officia do aliquip laboris voluptate consequat qui eu officia commodo eiusmod et dolore proident. Voluptate duis nulla irure dolore sunt ipsum laboris in veniam ad ea non.\r\n",
    registered: "2020-06-20T08:58:03 -06:-30",
    latitude: 11.913483,
    longitude: 161.972843,
    tags: ["dolor", "eiusmod", "et", "amet", "excepteur", "enim", "ex"],
    friends: [
      {
        id: 0,
        name: "James Campbell",
      },
      {
        id: 1,
        name: "Annmarie Herring",
      },
      {
        id: 2,
        name: "Conway Gibson",
      },
    ],
    greeting: "Hello, Letha Wood! You have 3 unread messages.",
    favoriteFruit: "apple",
  },
  {
    _id: "653958a8adacf55fe147e5f3",
    index: 6,
    guid: "7c9052cd-c549-4c81-87fc-76e7f1a67e8c",
    isActive: false,
    balance: "$3,073.95",
    picture: "http://placehold.it/32x32",
    age: 24,
    eyeColor: "brown",
    name: "Bridget Parker",
    gender: "female",
    company: "OVERPLEX",
    email: "bridgetparker@overplex.com",
    phone: "+1 (977) 546-3446",
    address: "248 Bills Place, Ruffin, Maryland, 6349",
    about:
      "In elit pariatur labore elit veniam nostrud cillum. Eu sunt amet quis minim et ipsum anim duis consectetur laboris aliqua deserunt cupidatat do. Ut tempor amet eiusmod incididunt cillum ut et.\r\n",
    registered: "2018-07-12T04:00:51 -06:-30",
    latitude: -48.448203,
    longitude: -168.371219,
    tags: ["eu", "ut", "ut", "tempor", "aliqua", "enim", "anim"],
    friends: [
      {
        id: 0,
        name: "Downs Knowles",
      },
      {
        id: 1,
        name: "Valdez Harris",
      },
      {
        id: 2,
        name: "May Harrington",
      },
    ],
    greeting: "Hello, Bridget Parker! You have 9 unread messages.",
    favoriteFruit: "strawberry",
  },
];
